executors:
  node:
    parameters:
      image:
        type: string
        default: "10"
    docker:
    - image: circleci/node:<< parameters.image >>
      environment:
        TERM: xterm

aliases:
  e2e-executor: &e2e-executor
    docker:
    - image: cypress/browsers:chrome69
      environment:
        TERM: xterm

  restore_cache: &restore_cache
    restore_cache:
      name: Restore Yarn Package Cache
      keys:
      - v{{ .Environment.versionCache }}-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}

  install_node_modules: &install_node_modules
    run:
      name: Install Yarn Packages
      command: yarn install --frozen-lockfile

  save_cache: &save_cache
    save_cache:
      name: Save Yarn Package Cache
      key: v{{ .Environment.versionCache }}-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
      paths:
      - /home/circleci/.cache

  store_results: &store_results
    store_test_results:
      path: results

  store_results_artifacts: &store_results_artifacts
    store_artifacts:
      path: results

version: 2.1

jobs:
  lint:
    executor: node
    steps:
    - checkout
    - <<: *restore_cache
    - <<: *install_node_modules
    - <<: *save_cache
    - run:
        name: Run ESLint
        command: yarn lint:ci
    - <<: *store_results
    - <<: *store_results_artifacts

  e2e_cypress:
    <<: *e2e-executor
    steps:
    - checkout
    - <<: *restore_cache
    - <<: *install_node_modules
    - <<: *save_cache
    - run:
        name: Run E2E tests
        command: yarn test:e2e:ci
    - <<: *store_results
    - <<: *store_results_artifacts
    - store_artifacts:
        path: cypress/videos
    - store_artifacts:
        path: cypress/screenshots

workflows:
  version: 2
  lint-test:
    jobs:
    - lint
    - e2e_cypress